### ISSUE TITLE
FIX-IT BETA TEST NOTES FROM CHRIS NOVY

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#144]
CHRIS > IF YOU NEED TO REACH HIM > He catches "everything" and is ideal beta runner!
One of my peeps!
Chris Novy > Mobile: (949) 629-5359 > chrisnovy@gmail.com

Feedback on order/checkout process along with Self & Team Discovery course REVIEW.

- [x] 1.) ###################
Home page title tag has "Academy"
<title]]>Cliff Michaels Academy Essentials for Life Leaders &amp; Entrepreneurs</title]]>

2. Purchase of All Access pass worked fine with exception of 3 issues:

- [x] Checkout Issue #1:
Change missing fields error message to red in checkout process. I didn't fill out my address and it took me a second to figure out what problem was (black erro text is sort of hidden amongst other text).

http://cliffmichaels.com/checkout/
Inline image 1

############
- [x] Checkout Issue #2:

WP Error/warning (below Order Details) when I clicked on view order:
Inline image 2

###########
- [x] Checkout Issue #3:
Email order confirmation:
from email is academy@cliffmichaels.com
from email name is "Cliff Michaels Academy"
Footer of email says "Cliff Michaels Academy"

############

- [x] Issue 4
Completion Certificate should say
                Cliff Michaels
Crash Course Completion Certificate

- [x] Issue 5
End of course should auto-advance to exam. Instead it auto-advanced to the survey. 

- [x] Issue 6: When survey was submitted, message said I didn't complete the course. Give students opportunity to take exam, then do the survey. (Note I get wanting to have feedback but if they haven't had an opportunity to take exam then asking survey questions about exam doesn't work)

#########
Issue 7
When grading the quiz, screen should auto-scroll to top where the exam results are listed. Instead after submitting exam answers, it stays at bottom of screen and leaves user to wonder how they scored.

###
- [x] Issue 8
Tools:
After passing the test, when I try to save content entered into the free tools, it gives message that I haven't passed the course:
<<<<
You can close this tool and return to it while in your current session. Unfortunatley you did not pass this course. Please try again. 
>>>>

- [x] After submitting challenge exercises, success message says I can review entries by going to the "My Toolkit". This is confusing: I was looking for a My Toolkit menu option in the header of page.
Suggest renaming "Free Tools" to "My Toolkit" and in the success message explaining to look on left hand side to view the "My Toolkit" section.

- [x] Users should be able to print out their toolkit entries. Recommend adding a "print" button
As a user I would find it annoying to fill out a tool and not be able to export it somehow. Currently only option would be to copy/paste into a word doc which creates formatting issues. Export of work users do should be easy so they can execute/implement the topic.

**Comment by cliffmichaelsgithub** [comment]
Was there anything Chris Novy suggested that we couldn't accommodate or can I send him back up to see if it all makes sense to him as user now. Also -- can you tell me how to take old tool out of system (eg PDF's with Academy logo need to be replaced with the corrected ones). I know how to add tool to product (I think) but not delete old ones.

**Comment by sethrubenstein** [comment]
You can send him back up Monday. There wasn't anything in this list we couldn't accommodate.

**Comment by cliffmichaelsgithub** [comment]
Cool. Will do
