### ISSUE TITLE
Cliff End of Year Tweaks

### ISSUE THREAD

**Issue by sethrubenstein** [PixelRocket-Biz/cliff-michaels#159]
- [x] Add verbiage about brainstormer on start free modal
- [x] Change Free Tools to "Cool Tools"
- [x] Add an additional area for course exercises to separate from tools.
- [x] Add note to tools area in courses that says "You can save and access in my account"
- [x] Change "my toolkit" to "my saved tools & exercises"
- [x] Change "progress board" to "Group Progress & User Management"
- [x] Change name to have red background.
- [x] Change "view entries" in course tools area to "View saved entries" also 
- [x] If you go to a saved tool and nothing is there it should say "go back to course to create new entry"
- [x] Change view entries button in course to only display if you have any saved entries in that form.
- [x] Change edit entry to "View/Edit Saved Entry"

**Comment by sethrubenstein** [comment]
Note to self: Make sure Course Exercises header appears before Cool Tools Header

**Comment by cliffmichaelsgithub** [comment]
Running 5 minutes late

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 23, 2015, at 5:57 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #159<https://github.com/PixelRocket-Biz/cliff-michaels/issues/159>.

-
