### ISSUE TITLE
HOW DO PEOPLE KNOW HOW TO PRINT THEIR SAVED TOOLS?

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#163]
Will we have a PINT BUTTON ON the tool or exercise edit page?

**Comment by sethrubenstein** [comment]
Part of Chris Coveys notes - add a print button. Thats in my todo list for things to get out Sunday.

**Comment by cliffmichaelsgithub** [comment]
Thx.
