### ISSUE TITLE
Make video larger on 4 essentials

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#170]
Can we put the Book Title, sub and NY Times to the left above the video and the Audio Sample / Chapter Sample t teh right of the title / above the audible logo. This would take away the current dead white space under the video before the About Book section. YES? NO?

ALSO: The About Book section needs a BOLD HEADER eg:

ABOUT THE BOOK > In The 4 Essentials of Entrepreneurial Thinking, Cliff Michaels blah blah ...

![screen shot 2015-01-05 at 8 01 50 am](https://cloud.githubusercontent.com/assets/6202539/5615573/43f335b2-94b1-11e4-99a6-cb98b3c5e396.png)

**Comment by sethrubenstein** [comment]
I think the better solution is just making the video larger. I'll make that fix later this evening.

**Comment by cliffmichaelsgithub** [comment]
Ok
