### ISSUE TITLE
ADD CART FUNCTION: USER gets credit for prior purchases if they get all access pass

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#180]
eg: if they spent $150 on three prior courses, and the cost of all access pass is $500, they would see $350 as balance due at checkout since they get a credit for whatever they spent prior - YES? That way, no matter what price the all access pass is - eg: more expensive down the road when i add more content, they only get the credit of actual paid purchases. YES

**Comment by sethrubenstein** [comment]
Yes make sense. I'll add this to my workload for this weekend. This functionality will take a little longer than the rest of the work but it should be done by end of January for sure.

**Comment by cliffmichaelsgithub** [comment]
Cool. All the new sizzles will be up then and we are ready for hardcore push.


Cliff | 310-488-6422
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
Strategic Coach | Venture Consulting
Mortgages | Private Equity | Real Estate
LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels> | Twitter<twitter.com/CliffMichaels>
CliffMichaels.com<http://cliffmichaels.com> | CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>

**Comment by sethrubenstein** [comment]
Note to self:
Functionality wise....
Check users orders.
Tally up order total
Subtract total at checkout.
