### ISSUE TITLE
URGENT > COURSE AUDIO PROBLEMS = CAN'T HEAR > TEMPORARY or SERIOUS?

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#182]
Firefox works on audio and chrome does not - both have the player working perfectly since you can see the video? Is it a vimeo issue? Our website? Even after I close and same video or browser, i have same problem. I move on to another part of the same course. Same problem. This is happening throughout the website. Bummed since I was in flow to fix a ton and i sent people up there hoping they are not having issues too. i am flipping through every video of every course and every preview on the site to make notes of any final tweaks of slide changes for lee before we change them all out end of week.

**Comment by sethrubenstein** [comment]
I'm not having any issue with audio. Can you confirm anyone else is?

**Comment by cliffmichaelsgithub** [comment]
I will ask others -- can you do same?

**Comment by cliffmichaelsgithub** [comment]
Also -- when a user logs in on mobile, they can't see the "access course" button but if they click the title or image it will. Is there any way to ever get mobile experience to show a button or same word the laptop user sees to "preview on home page" or "access course" -- this is particularly important when I hit asia -- everyone lives on mobile -- many can't afford laptops

**Comment by cliffmichaelsgithub** [comment]
FYI:I re-booted computer - cleared cache and history. Logged out. logged back in. Still can get audio on chrome on my website but i can with firefox and safari - WTF

**Comment by cliffmichaelsgithub** [comment]
Do you have 5 minute to talk - I have a ton of work to do on the set and I am stuck - non-related to the audio issue which I can work on firefox in the mean tie ... butI don't understand why 4 Essentials course isn't showing the exercises. Also ... I don't know why in self discovery I see the two colums to select name of tool and then view of tool ... but that option was not there for 4 Essentials exercises in the admin part. I have a hard time explaining this so not sure you will follow without a 5 minute call.


Cliff | 310-488-6422
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
Strategic Coach | Venture Consulting
Mortgages | Private Equity | Real Estate
LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels> | Twitter<twitter.com/CliffMichaels>
CliffMichaels.com<http://cliffmichaels.com> | CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>

**Comment by sethrubenstein** [comment]
@cliffmichaelsgithub Take a look at the 4 essentials now course exercise bug fixed. Also just as a caveat because that was a separate issue from your audio bug this should be filed as a separate github issue.

**Comment by sethrubenstein** [comment]
As for the 2 columns in the tool and exercise selection. We went over that before. Basically you need to select both in one line. So if I'm selecting ToolA i need to put that in both fields. One field calls the form the other calls the "view/edit form entry" link. All you need to know is put whatever youre selecting in one field in the same dropdown to the right.

**Comment by cliffmichaelsgithub** [comment]
Yes - sorry - rushing here to fix a lot

**Comment by sethrubenstein** [comment]
If you need another call to walk through anything I'm unavilable till about 5:30pm my time eastern so 2:30pm your time.

**Comment by cliffmichaelsgithub** [comment]
I get that but that's wjat I'm telling you -- the option wasn't there in the 4 essentials to select a view -- as it was for the other course products. I know the drill now but that one didn't work - appear ??

**Comment by cliffmichaelsgithub** [comment]
2:30! Boom. Let's do it. Just 10-15 mins should do

Cliff | 310-488-6422
Cliff Michaels & Associates
VC, Mortgages, Real Estate
E-Learning, Forums & Retreats
Training for Careers & Entrepreneurs
CliffMichaels.com<http://cliffmichaels.com>
The4Essentials.com
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
LinkedIN<linkedin.com/in/cliffmichaels> Facebook<Facebook.com/cliffmichaels> Twitter<twitter.com/CliffMichaels>






On Jan 15, 2015, at 11:15 AM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


If you need another call to walk through anything I'm unavilable till about 5:30pm my time eastern so 2:30pm your time.

-
