### ISSUE TITLE
SAFARI VIEW IS Jacked up at login of account - see screen shot

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#183]
![screen shot 2015-01-14 at 7 30 10 pm](https://cloud.githubusercontent.com/assets/6202539/5752118/ee366520-9c23-11e4-8473-eacb5a3845a7.png)

**Comment by sethrubenstein** [comment]
I see this bug. I should have a fix for it this evening.

**Comment by cliffmichaelsgithub** [comment]
Thanks.
