### ISSUE TITLE
START FREE POP UP

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#186]
- [x] headline on the pop up should read "Complete form to get Cliff's FREE tips, tools, brainstormer, special e-courses & more!
- [x] see attachment - it also says "or complete form below" after it says "Complete form ..."
- [x] DELETE that extra line does not belong there, right? 
![screen shot 2015-01-19 at 12 11 59 pm](https://cloud.githubusercontent.com/assets/6202539/5807090/8cbe8fe8-9fd4-11e4-8eea-38dbf359800f.png)

**Comment by sethrubenstein** [comment]
@cliffmichaelsgithub You already have an existing ticket for this please double check all existing tickets. https://github.com/PixelRocket-Biz/cliff-michaels/issues/172

**Comment by cliffmichaelsgithub** [comment]
SORRY - I COULD NOT FIND IT

**Comment by cliffmichaelsgithub** [comment]
but it's an easy fix so feel free to delete whichever one works for you

**Comment by cliffmichaelsgithub** [comment]
The prior one did not have these subtle corrections.

**Comment by sethrubenstein** [comment]
K will do.

**Comment by cliffmichaelsgithub** [comment]
Looks like easy text fix

**Comment by sethrubenstein** [comment]
Yea. Most of the tickets in the January https://github.com/PixelRocket-Biz/cliff-michaels/milestones/January%202015 sprint will be finished and up tonight.

**Comment by cliffmichaelsgithub** [comment]
Cool - thx!

**Comment by sethrubenstein** [comment]
@cliffmichaelsgithub The reason you see "or complete form below" without any context is because you're currently logged in. If you were to log out you'd see social login buttons below as option 1 OR complete the form below.

**Comment by cliffmichaelsgithub** [comment]
Got it. I see. Can you still update the header phrase >> Get Cliff's FREE tips, tools, brainstormer, special e-courses & MORE!
