### ISSUE TITLE
URGENT: NEGOTIATION COURSE VIDEO 7 DOES NOT LOAD

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#190]

**Comment by sethrubenstein** [comment]
Video loads fine by me see screencast of it working here http://recordit.co/b7xEqwWHjV

**Comment by cliffmichaelsgithub** [comment]
Why do you suppose me, Chris, and gisselle all had separate issues loading that same video 7 on sake course at different times on different computers in different cities. That can't be a coincidence when most others worked.

**Comment by sethrubenstein** [comment]
No idea. Could have been a vimeo hickup. But I can't recreate and problem. Are you still having trouble playing that video?

**Comment by cliffmichaelsgithub** [comment]
I did as of last night. Also can't login on my cell phone for some reason. Will Try again in 5 minutes on both

**Comment by cliffmichaelsgithub** [comment]
No problem - it worked just nowpn laptop. But I always have trouble logging in on cell. Any idea what's up with that?
