### ISSUE TITLE
HOME PAGE HEADER IMAGE & QUOTE SIZE

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#200]
![jpeg3heads](https://cloud.githubusercontent.com/assets/6202539/6114710/dee5279c-b054-11e4-88d9-442f9da2165c.jpeg)
![cliff leftstage](https://cloud.githubusercontent.com/assets/6202539/6114712/e42f243c-b054-11e4-8ff6-99a5d777465b.jpeg)

- [x] add Jen's new home page header image
- [x] bump up size of quote under the red start button - were we able to make this a rotating quote or does that hurt the download performance?

**Comment by cliffmichaelsgithub** [comment]
i uploaded three images. This one is the full home page header
![homepageheader](https://cloud.githubusercontent.com/assets/6202539/6114745/15e8a50c-b055-11e4-946a-ddb9a976da4a.jpeg)

**Comment by cliffmichaelsgithub** [comment]
The home p
![screen shot 2015-02-11 at 1 39 42 pm](https://cloud.githubusercontent.com/assets/6202539/6157073/8d23546a-b1f3-11e4-9bb6-8797e331e17d.png)
age header is chopped off on both sides. Doesn't look right

**Comment by sethrubenstein** [comment]
You'll need to edit the image then, you've got a good deal of black space in between there.

**Comment by sethrubenstein** [comment]
Let me know when you have it edited and I'll switch it out.

**Comment by cliffmichaelsgithub** [comment]
Shit! Very hard to reach Jen again these days. Ca we simply use the individual images and make them work together -- or fill the middle space. I also didn't expect it to be so dark up the middle ?

**Comment by sethrubenstein** [comment]
No as I mentioned when you brought this up it has to be one large image. I can maybe get rid of some of the dark space. Give me a few minutes.

**Comment by cliffmichaelsgithub** [comment]
Can you easily switch back for now. Looks bad

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 1:43 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:

You'll need to edit the image then, you've got a good deal of black space in between there.

**Comment by cliffmichaelsgithub** [comment]
We gave you one large + 2 small just in case. Let me know for sure before I go back to jen

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 1:45 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


No as I mentioned when you brought this up it has to be one large image. I can maybe get rid of some of the dark space. Give me a few minutes.

-

**Comment by cliffmichaelsgithub** [comment]
Fyi: github does not let me sign in or reply via my cell phone. I can only reply regular cell phone email - so I'll try to delete my signature each time



On Feb 11, 2015, at 1:45 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


No as I mentioned when you brought this up it has to be one large image. I can maybe get rid of some of the dark space. Give me a few minutes.

-

**Comment by sethrubenstein** [comment]
Okay @cliffmichaelsgithub take a look at that .

**Comment by cliffmichaelsgithub** [comment]
better - can the welcome move to the right a bit - and me back to the left a bit so my face isn't cut off - i realize it will get resized but in general we want to account for some margin of sizing without my face getting cut off. I actually think the two heads on right look better than 3 (less busy) so that's a happy accident. Although curios if their head size can be reduced (if you know how - or if jen can on next iteration).

**Comment by cliffmichaelsgithub** [comment]
Did you resize the 1 large image or play with the 2 individual images?

**Comment by cliffmichaelsgithub** [comment]
Occurs to me that instead of Forums & Retreats, we should use the word Cliff Live because although the icons are equidistant, the title words are not. 
ALSO - to make the image on the right work a little better >>. it will help to shorten the 3rd Icon Title >> Instead of Forums & Retreats on the top line ... edit to ...
             Cliff Live
     Forums & Retreats
Schools. Clubs. Companies

![screen shot 2015-02-11 at 1 59 21 pm](https://cloud.githubusercontent.com/assets/6202539/6157446/42612468-b1f6-11e4-8964-00917e27b2b3.png)

**Comment by cliffmichaelsgithub** [comment]
Currently  - the red button is actually not centered on the page so there is room to pull the Welcome to the right and the Cliff Live (formerly Forums & Retreats( to the left) a bit - assuming I didn't just create a mind fuck for you? I never know what's easy or hard

**Comment by sethrubenstein** [comment]
No the red button is 100% centered on the page. 
No had to use the 1 large image and just cut out the middle some - I can try pulling your face to the right some more - look for that in like 5 min.

**Comment by sethrubenstein** [comment]
K take a look now ive moved the image to the right some.

**Comment by cliffmichaelsgithub** [comment]
I stepped out and it doesn't show on mobile at all. The black is a bit harsh too. I'll see if jen can re-do. When back I'll look. When you said move my head to right I think you meant left (of the welcome). More to the right moves it more into the welcome image

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 2:17 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


K take a look now ive moved the image to the right some.

-

**Comment by sethrubenstein** [comment]
Yea it probably wont show on mobile bc of the way your image is. Honestly having an image like I had before is the best way to go. Thats why I recommend you just get a nice big photo of you in some teaching/speaking environment with other people in it but you front and center.

**Comment by cliffmichaelsgithub** [comment]
I'm frustrated. I thought we did a single image the way you asked. How is your image different? I need help with this. We have an image of me speaking. That left stage angle shot is as good as it gets. What else can we do with that?

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 3:09 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Yea it probably wont show on mobile bc of the way your image is. Honestly having an image like I had before is the best way to go. Thats why I recommend you just get a nice big photo of you in some teaching/speaking environment with other people in it but you front and center.

-

**Comment by sethrubenstein** [comment]
You provided a single image but its split up and it just doesnt work well as a background. Look at the difference between these two images. 

![bigstock-business-meeting-manager-di-37064878](https://cloud.githubusercontent.com/assets/180264/6158663/a55a5d90-b21a-11e4-94d3-42526ced7c57.jpg)

Do you see how my original image is large enough that it can work more vertically or horizontally because theres people all throughout the image so pretty much no matter where you position the image itll be good.


Then theres the image you guys have:
![cliffmasthead](https://cloud.githubusercontent.com/assets/180264/6158670/bb63c4a0-b21a-11e4-93e1-a49333f75afb.jpg)

It's slender and it has people in basically the 2 sides of the image. No matter what you try to do that image just wont work both aesthetically and mathematically with repositioning on various sizes for different screen.

**Comment by cliffmichaelsgithub** [comment]
Is it because it needed more free space at the top? This is not my area of expertise. When I saw the way Jen laid it ut over the text, everything looked great ... I was to the left of the welcome.I see a solution but need to talk it out loud - can't do it via email instructions... easier to point my cursor


Cliff Michaels & Associates | 310-488-6422
Mortgages | Private Equity | Real Estate
Strategic & Venture Consulting
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com> | LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels>

**Comment by cliffmichaelsgithub** [comment]
Can you show e the old screen shot of yours with text?

I'll talk to jen one more time but I thin there may be a 5 minute solution for you and me


Cliff Michaels & Associates | 310-488-6422
Mortgages | Private Equity | Real Estate
Strategic & Venture Consulting
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com> | LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels>

**Comment by sethrubenstein** [comment]
I've reverted back to the old image so you can see it.

**Comment by cliffmichaelsgithub** [comment]
Thx. Scarfing down late lunch. Will look again in a bit

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 3:30 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


I've reverted back to the old image so you can see it.

-

**Comment by cliffmichaelsgithub** [comment]
Can we chat 5-10 minutes anytime ?

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 3:30 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


I've reverted back to the old image so you can see it.

-

**Comment by sethrubenstein** [comment]
We can do tomorrow evening 9pm Eastern.

**Comment by cliffmichaelsgithub** [comment]
Ok. See icon title / subtitle below > Can we do 2 minutes now - so I know what to tell justin - he's the only one I might be able to ask tonight but I need  written instruction on size / resolution etc because I don't know what jen did wrong. What you're showing me as final result is totally different than what she showed me. Separately - I do want to change that first subtitle & third title & subtitle  to ...

             Cliff Live
      Forums & Retreats
Clubs. Schools. Companies.

             Welcome
             About Cliff
        Mission & Giving



Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 3:44 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


We can do tomorrow evening 9pm Eastern.

-

**Comment by cliffmichaelsgithub** [comment]
Seth -- Justin can work on this now. Can you make those two minor icon / title / subtitle changes so he's looking at the exact same words on page I want to end up with.

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 3:22 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


You provided a single image but its split up and it just doesnt work well as a background. Look at the difference between these two images.

[bigstock-business-meeting-manager-di-37064878]<https://cloud.githubusercontent.com/assets/180264/6158663/a55a5d90-b21a-11e4-94d3-42526ced7c57.jpg>

Do you see how my original image is large enough that it can work more vertically or horizontally because theres people all throughout the image so pretty much no matter where you position the image itll be good.

Then theres the image you guys have:
[cliffmasthead]<https://cloud.githubusercontent.com/assets/180264/6158670/bb63c4a0-b21a-11e4-93e1-a49333f75afb.jpg>

It's slender and it has people in basically the 2 sides of the image. No matter what you try to do that image just wont work both aesthetically and mathematically with repositioning on various sizes for different screen.

-

**Comment by cliffmichaelsgithub** [comment]
WILL THIS WORK ?
![cliff curtain call](https://cloud.githubusercontent.com/assets/6202539/6174129/ba6aff6e-b2a1-11e4-92fe-74f686e0b654.jpg)

**Comment by sethrubenstein** [comment]
Yes we're still on for 9pm eastern.
No that image really doesnt work - see screenshot here https://cloudup.com/c22Ue8HcAuK

**Comment by cliffmichaelsgithub** [comment]
DAMN! CAN WE TALK SOONER?
ANY BREAK IN THE DAY?






Cliff Michaels & Associates | 310-488-6422
Mortgages | Private Equity | Real Estate
Strategic & Venture Consulting
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com> | LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels>

**Comment by sethrubenstein** [comment]
I can probably do an hour and a half earlier at 7:30pm Eastern.

**Comment by cliffmichaelsgithub** [comment]
Whenever I try to login to GitHub from cell phone I get this >> I also don't know if github has an app for iPhone ? There are several github apps but I think maybe they're for developers

What?

Your browser did something unexpected. Please contact us if the problem persists.

Contact Support<https://github.com/contact> - GitHub Status<https://status.github.com/> - @githubstatus<https://twitter.com/githubstatus>
[X]<https://github.com/>
<https://github.com/>

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 11, 2015, at 2:17 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


K take a look now ive moved the image to the right some.

-

**Comment by cliffmichaelsgithub** [comment]
re: keeping things as simple as possible >> sign up should say:

 START LEARNING
FREE tools & videos

Sign with FB or Google
First Name | Last Name
Email        |       Password
by submitting, you accept terms


On Feb 11, 2015, at 2:17 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


K take a look now ive moved the image to the right some.

-
