### ISSUE TITLE
I am not seeing current web page i designed even after cache cleared for Cliff Live?

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#201]

**Comment by sethrubenstein** [comment]
Whats the url you are trying to hit?

**Comment by cliffmichaelsgithub** [comment]
No worries on that. Must have been temporary glitch.

Cliff > 310-488-6422
VC | Mortgages | Private Equity
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 10, 2015, at 6:37 AM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Whats the url you are trying to hit?

-
