### ISSUE TITLE
CAN'T EDIT MY BLOG - PREPARING TO PUT IT BACK UP SOON

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#203]
WOULD LIKE THE BLOG TO HAVE THE SAME BANNER AS HOME PAGE - ME ON LEFT - PEOPLE ON RIGHT. NICELY FORMATTED INTO THAT WHOLE RECTANGLE IF POSSIBLE. YES? NO? IF NOT - JUST THE PHOTO OF ME ON LEFT
![homepageheader](https://cloud.githubusercontent.com/assets/6202539/6156340/2bfb4ddc-b1ee-11e4-9047-3a3fe710805b.jpeg)
![cliff leftstage](https://cloud.githubusercontent.com/assets/6202539/6156339/2bf98704-b1ee-11e4-9cf7-af52e34dd22d.jpeg)
![jpeg3heads](https://cloud.githubusercontent.com/assets/6202539/6156341/2bfd0ce4-b1ee-11e4-8c28-c8e85f3d06a9.jpeg)

**Comment by sethrubenstein** [comment]
I dont understand what the request is. You can't edit your blog or you want to put this image somewhere on your blog?

**Comment by cliffmichaelsgithub** [comment]
I can't edit my main blog page - you'll notice I changed the text that supposed to be in the header area but it didn't change - and yes - I wanted to fix that banner once and for all with a proper sized photo image


Cliff Michaels & Associates | 310-488-6422
Mortgages | Private Equity | Real Estate
Strategic & Venture Consulting
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com> | LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels>

**Comment by cliffmichaelsgithub** [comment]
Priority os the home page banner - not the blog. But I assume the blog is same process?


Cliff Michaels & Associates | 310-488-6422
Mortgages | Private Equity | Real Estate
Strategic & Venture Consulting
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com> | LinkedIN<linkedin.com/in/cliffmichaels> | Facebook<Facebook.com/cliffmichaels>

**Comment by sethrubenstein** [comment]
Based on our talking the other night where you realized the image you were providing wouldnt work as a background and we have an existing nicely cut out image I'm going to go ahead and close this out.

**Comment by cliffmichaelsgithub** [comment]
I'm unclear what you mean by existing cut out? I don't like the blog page header (although it's not urgent)

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 13, 2015, at 9:08 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Based on our talking the other night where you realized the image you were providing wouldnt work as a background and we have an existing nicely cut out image I'm going to go ahead and close this out.

-
