### ISSUE TITLE
ONCE LOGGED IN - YOU STILL SEE START FREE ON HOME PAGE - SEE SCREENSHOT

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#216]
![screen shot 2015-02-20 at 2 34 58 pm](https://cloud.githubusercontent.com/assets/6202539/6310655/e7a746a0-b90d-11e4-9dee-47007d8d1096.png)

**Comment by sethrubenstein** [comment]
Yea thats because thats whats there. We've never switched that out for anything else if logged in.

Also please be sure to not have caps lock on when posting to github it just throws me off when I'm looking at list of issues.

**Comment by cliffmichaelsgithub** [comment]
Gotcha -- sorry about that. Do these look like easy fixes. One of my beta testers was spotting issues and I'm on phone with her now - user Tardehali

**Comment by sethrubenstein** [comment]
The white text thing is an easy fix, deploying it now. This ticket isn't a bug theres not a bug here its a request for you're logged in so what do you want me to have there instead. So let me know what you want to appear in this center spot when someone is logged in and I can add it in.

**Comment by cliffmichaelsgithub** [comment]
for that vacated space > here are the ideas
Sponsor a Student or School - or tat becomes the third box on the right as I mentioned earlier and we have a product feature up the middle such as The All Access Pass.?

**Comment by sethrubenstein** [comment]
Sure, we could put the All Access Pass in there but that might not make a lot of sense if someone bought that course? Would you rather put something there like a welcome message, welcome to cliff michaels.com etc etc...

**Comment by cliffmichaelsgithub** [comment]
Since Welcome is on the left, we wouldn't include it again. Let me think on that a minute

**Comment by cliffmichaelsgithub** [comment]
ALSO: Can the field box for last name say "Last name" just as the field box for first name says "Name". Can each box properly be labeled - first name / last name?

**Comment by cliffmichaelsgithub** [comment]
Tina received user confirmation with automated password and link to login. That link takes her to back end of wordpress. Then asked to put in user name and password - it doesn't take her to our website. It takes her t a dash board where she's given option to change colors, etc. She will send a screenshot or can you see the problem

**Comment by cliffmichaelsgithub** [comment]
SOLUTION FOR THE VACATED HOME PAGE SPACE - Let's stick with the three box formula i just proposed earlier today >> but rotate one to the middle after they login (eg: Buy E-Courses button becomes a larger box in the middle with a message of Group Discounts Available! Or "Sponsor a School or Student". Call me to discuss.

**Comment by cliffmichaelsgithub** [comment]
FYI: In both safari and chrome most recent versions Tia says the website is incredibly slow to load - is that because you are working on it?

**Comment by sethrubenstein** [comment]
I am currently working on things. As for the field names you asked me to remove the first and last name field labels. I can re-add them back. As for being pushed to the wordpress backend let me take a look into that.

When she signed up she should have automatically been signed in though correct?

**Comment by sethrubenstein** [comment]
Okay I've got a fix for the wordpress redirect I figured out what was wrong there - I'm working on now should be out in a few hours.

**Comment by sethrubenstein** [comment]
Okay the wordpress redirect and the weird wording when you complete the signup form has been fixed and is out.

**Comment by cliffmichaelsgithub** [comment]
Thanks. What's your verdict on how we fill the vacated "start free" spot after someone logs-in? I think for now it should say go to "Sponsor a Student or School". This this a third box I really want to incorporate anyway since it can be a huge revenue builder.

**Comment by cliffmichaelsgithub** [comment]
Re: the field boxes > it's ok to have the words "First Name" "Last Name" above or in their respective box. What was weird before was when it was under the field box taking up extra vertical space. Tina noted that it wasn't clear if both boxes needed to be filled in since the last name field box didn't have a header / asterisk like first name field box

**Comment by cliffmichaelsgithub** [comment]
How about this after they login > 
Sponsor a School or Student
with an All Access Pass >
