### ISSUE TITLE
WEBSITE IS VERY SLOW

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#219]
I received sereval error messages > here's one that happened when i went to edit Cliff Live page in WP admin
![screen shot 2015-02-20 at 6 02 11 pm](https://cloud.githubusercontent.com/assets/6202539/6312373/efcb9f6c-b92a-11e4-9814-64fb4f045a7a.png)

**Comment by sethrubenstein** [comment]
Gateway timeout isn't related to the server its the connection you have to the server. I'm not having any issues with the speed of the site and the server actually has low usage right now so theres no server problem.

**Comment by cliffmichaelsgithub** [comment]
Tina had same issue in San Francisco

**Comment by sethrubenstein** [comment]
This may be a pacific region thing. Basically whats happening when you get a gateway timeout is this.

We have currently 1 server located here in DC. Then we have caching servers all over the place. When you hit the site you're hitting a caching server that sees if theres a cached version of that page if it finds it it uses it if it doesnt then it hits the actual server in DC. 

So what this sounds like is the pacific caching server isnt connecting to the DC server. I'll check with the provider to see if theres anything up.

**Comment by cliffmichaelsgithub** [comment]
Just got this message -- I have been trying to edit simple text on pages for a while and can't. So I;ll have dnner and try again later. see screenshot - this one is new >>
![screen shot 2015-02-20 at 6 16 26 pm](https://cloud.githubusercontent.com/assets/6202539/6312431/ec1a9d4e-b92c-11e4-9010-e66b0301efbd.png)

**Comment by sethrubenstein** [comment]
Yea why dont you try again in the morning and let me figure out whats goin on with the caching server.

**Comment by cliffmichaelsgithub** [comment]
Tina had same issue - its not our connection - we both tried on chrome and safari and we cleared cached and rebooted ... let me know what you think of idea for filling the vacated space after login >> I put that in teh appropriate Github message

**Comment by sethrubenstein** [comment]
Right but youre both in California so youre hitting the same caching server

**Comment by cliffmichaelsgithub** [comment]
LOL - either way - me no likey the slow pokey site

**Comment by sethrubenstein** [comment]
Check again this morning I don't see anything wrong in the west coast caching.

**Comment by cliffmichaelsgithub** [comment]
Should we be concerned about starting off on wrong foot. We've never had traffic but in teh few instances I have had beta users, the slow load factor has been a problem half the time. Does that speak negatively about our server issues from the start since you mentioned doing something a while back that was supposed to increase speed, etc.?

**Comment by sethrubenstein** [comment]
Well we really wont know until you have more beta testers. The work that
youre talking about is the work I did to make the actual course pages load
much quicker than before because we don't load the videos until you
actually click on the thumbnail to start each video - before all videos
were being preloaded.

**Comment by sethrubenstein** [comment]
It might be worth looking into beefing up the server infrastructure - keep
in mind right now you're in a medium performance server that I have running
other sites because I run the server for you for free right now. So when
youre actually launching and actually getting more and more sells well
probably want to talk about spinning up server infrastructure just for you.

**Comment by cliffmichaelsgithub** [comment]
Ok. Thanks. Let's kill that as a current issue but watch for feedback.


On Feb 22, 2015, at 6:15 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:

Well we really wont know until you have more beta testers. The work that
youre talking about is the work I did to make the actual course pages load
much quicker than before because we don't load the videos until you
actually click on the thumbnail to start each video - before all videos
were being preloaded.
On Feb 22, 2015 4:11 PM, "cliffmichaelsgithub" <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Should we be concerned about starting off on wrong foot. We've never had
> traffic but in teh few instances I have had beta users, the slow load
> factor has been a problem half the time. Does that speak negatively about
> our server issues from the start since you mentioned doing something a
> while back that was supposed to increase speed, etc.?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/PixelRocket-Biz/cliff-michaels/issues/219#issuecomment-75458404>
> .
>

-

**Comment by cliffmichaelsgithub** [comment]
Ok. Cost to have a non-shared server?

**Comment by cliffmichaelsgithub** [comment]
Let's discuss along with other issues monday once I understand potential cost / benefit of Microsoft Outlook CRM vs Zoho

**Comment by sethrubenstein** [comment]
K.  FYI I'm running some server optimizations the next hour and a half. So
you may see things flicker in and out.

**Comment by cliffmichaelsgithub** [comment]
I won't be online. No worries. My primary goals tomorrow are finalizing the before / after login experience. Plus these comments from Rob Richman are valid. He's important > my main Zappos connection - he was Tony Hsieh's main inside culture creator

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 22, 2015, at 6:39 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:

K. FYI I'm running some server optimizations the next hour and a half. So
you may see things flicker in and out.
On Feb 22, 2015 9:22 PM, "cliffmichaelsgithub" <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Let's discuss along with other issues monday once I understand potential
> cost / benefit of Microsoft Outlook CRM vs Zoho
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/PixelRocket-Biz/cliff-michaels/issues/219#issuecomment-75481090>
> .
>

-

**Comment by sethrubenstein** [comment]
#224
