### ISSUE TITLE
Create Digital Ocean Infastructure

### ISSUE THREAD

**Issue by sethrubenstein** [PixelRocket-Biz/cliff-michaels#224]
Need load balancer - auto scaling - and memcache.

Setup script: https://rtcamp.com/easyengine/
Need to get this plugin for Cliff for caching: http://wp-rocket.me/

**Comment by sethrubenstein** [comment]
Start with W3 Total Cache

**Comment by sethrubenstein** [comment]
@cliffmichaelsgithub You'll start seeing charges this month on your credit card for the new server infrastructure. At first ti'll be around 10-20 but when we go live with it it'll be around 40 a month. There will also be a $39 charge for setting up a new caching layer for the site.

**Comment by cliffmichaelsgithub** [comment]
What entity bills my card for new server? Cc Cindy please.

On Mar 8, 2015, at 12:34 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


@cliffmichaelsgithub<https://github.com/cliffmichaelsgithub> You'll start seeing charges this month on your credit card for the new server infrastructure. At first ti'll be around 10-20 but when we go live with it it'll be around 40 a month. There will also be a $39 charge for setting up a new caching layer for the site.

-

**Comment by sethrubenstein** [comment]
That'll be digital ocean for the monthly charges and WP Rocket for the one time caching setup.
