### ISSUE TITLE
Home Page Rotating Quotes under the Welcome Back

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#229]
To fill some of that dead space under the buttons after someone logs in, should we put the rotating quotes. Hardy, Hsieh, Logan, Mycoskie quotes would be great.

![screen shot 2015-02-27 at 1 10 57 pm](https://cloud.githubusercontent.com/assets/6202539/6421308/73fe7f64-be82-11e4-8828-6f6cf2d70266.png)

**Comment by sethrubenstein** [comment]
So based on what we talked about I've come up with a super simple solution.

We're just gonna move the testimonials up directly under the header. We have the nice big buy ecourses now so theres no reason to presume that we need to have the courses right under the header.

**Comment by cliffmichaelsgithub** [comment]
Sounds good
