### ISSUE TITLE
SPONSOR PAGE

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#230]
Instead of giving them the option to sponsor in $5 increments, can we ask them to check box a sponsor level such as the levels I have listed on the sponsor page (either as past of the form or what get's added to teh cart with button choices?)
![screen shot 2015-02-27 at 1 45 30 pm](https://cloud.githubusercontent.com/assets/6202539/6421805/31c54056-be87-11e4-910b-f32d8872b3a9.png)

**Comment by sethrubenstein** [comment]
Yes.

**Comment by cliffmichaelsgithub** [comment]
Cool! I think that makes it easier!

**Comment by sethrubenstein** [comment]
I've done one better for you. I've created it such that this runs through woocommerce and people can just type in whatever amount they want.

**Comment by cliffmichaelsgithub** [comment]
Understood - I saw how we had it - but that was also creating some confusion - can we give them the sponsor levels as buttons to choose or at the bottom leave that open field as "or choose any amount and we'll pick a school for you!" It makes it easy when people dong have to think and they can see what their donation buys.

**Comment by sethrubenstein** [comment]
You can edit that page and put some suggested levels, I put a suggested starting price of 25.00 but they can now enter whatever they want.

**Comment by cliffmichaelsgithub** [comment]
I get what you're saying - just wondering if there's an easy way to add those 6 levels as buttons with actual description but as long as we fix the confusing part -- when i put in $5 it tried to charge $25. Then I realized why that structure was weird - it's like "how many $5" products ? Trying to eliminate that confusion for user

**Comment by cliffmichaelsgithub** [comment]
I have bullet suggestions (students won't want to spend more than $10-20. But collecting a lot of those could be great cash flow -- kind of like suggested donation for students helping students $10! Suggest sponsorship for parents, professionals & institutions $50-500. Philanthropists and change heroes > $1000-10,000

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 28, 2015, at 11:00 AM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


You can edit that page and put some suggested levels, I put a suggested starting price of 25.00 but they can now enter whatever they want.

-

**Comment by cliffmichaelsgithub** [comment]
I'll be working on content all weekend so ping me if you want me to look at anything

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 28, 2015, at 11:00 AM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


You can edit that page and put some suggested levels, I put a suggested starting price of 25.00 but they can now enter whatever they want.

-

**Comment by cliffmichaelsgithub** [comment]
![screen shot 2015-02-28 at 12 51 51 pm](https://cloud.githubusercontent.com/assets/6202539/6428114/c2756a8c-bf49-11e4-9bb8-d7b464ee36ed.png)

**Comment by cliffmichaelsgithub** [comment]
- [ ] On the cart page > Change "DONATION" to Choose Your Sponsor Level

![screen shot 2015-02-28 at 12 51 51 pm](https://cloud.githubusercontent.com/assets/6202539/6428114/c2756a8c-bf49-11e4-9bb8-d7b464ee36ed.png)
