### ISSUE TITLE
SPONSOR PAGE - LEVELS

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#231]
Instead of option to sponsor in $5 increments, can we provide check box or sponsor level buttons as I have listed on the sponsor page?
![screen shot 2015-02-27 at 1 45 30 pm](https://cloud.githubusercontent.com/assets/6202539/6421805/31c54056-be87-11e4-910b-f32d8872b3a9.png)

**Comment by sethrubenstein** [comment]
Duplicate.
