### ISSUE TITLE
My Curses Page > Progress Monitor

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#233]
See screenshot - word donation appears? why?
Also - anywhere we have the word donation needs to change to Sponsor.
![screen shot 2015-03-05 at 3 36 26 pm](https://cloud.githubusercontent.com/assets/6202539/6517248/f962c280-c34d-11e4-8ad7-35109d03564d.png)

**Comment by sethrubenstein** [comment]
Ah good catch. Thats because I added the donation product type. I'll hide that in the front end.
