### ISSUE TITLE
My Saved Tools & Exercises are going NOWHERE

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#234]
![screen shot 2015-03-05 at 3 39 38 pm](https://cloud.githubusercontent.com/assets/6202539/6517275/40fbacba-c34e-11e4-8c6b-8d3a416d4981.png)
most say "no match" like below weras the one above just has a blank header
![screen shot 2015-03-05 at 3 40 32 pm](https://cloud.githubusercontent.com/assets/6202539/6517287/587e6832-c34e-11e4-90f4-6e8802580c3a.png)

**Comment by sethrubenstein** [comment]
1. The first one doesnt say no entries because that view wasnt setup correctly, you and I should go over that again for your notes.
2. I can change the language so that says "You have no saved data for this (Exercise or Tool) please go to the requisite course to complete"

**Comment by sethrubenstein** [comment]
Re: 1 I've gone ahead and setup that view so its correct now.

**Comment by cliffmichaelsgithub** [comment]
A few more little TOOLS problems - NEED ASAP. NEW ISSUE?
1.) The saved date of a tool is 24 hours ahead and still has the weird / format.
2.) Not given option to save name of tool
3.) see screenshot - I went to edit my tool AFTER SAVING and it saved as a fatal error message
![screen shot 2015-03-05 at 4 42 04 pm](https://cloud.githubusercontent.com/assets/6202539/6518091/fc94bdce-c356-11e4-9ef8-acff0a6d7c40.png)

**Comment by sethrubenstein** [comment]
On point 2. you need to add a title field to that tool you didn't create one when you created the form.

I'll look into point 3 and 1 as soon as I can.

**Comment by cliffmichaelsgithub** [comment]
There wasn't an option to name the tool. Also -- you have "see your entries under exercises but that same message is not available under tools. Also - here with Chase Mirkovitz - nothing but problems with his user experience. Almost too much to keep typing. Now he can't login and gets the wordpress back end message that says ERROR - incorrect user name. He clicked on lost password -- and then it still gae hi the wait to login 19 minutes message. Very frustrating

**Comment by cliffmichaelsgithub** [comment]
Also - I'm here with Chase Mirkovitz - nothing but problems with his user experience so far. he's the one finding all these errors on the course experience. Now he can't login and gets the wordpress back end message that says ERROR - incorrect user name. He clicked on lost password -- and then it still gave him the "wait to login 19 minutes" message. Very frustrating. Do you have 15 minutes talk with us.

**Comment by cliffmichaelsgithub** [comment]
WE NEED HELP - CANT LOGIN

**Comment by sethrubenstein** [comment]
Yea let me get somewhere quiet - call you in 3 min.

**Comment by sethrubenstein** [comment]
Updated plugin. This seems to have resolved bug.
