### ISSUE TITLE
Add up sell to account page

### ISSUE THREAD

**Issue by sethrubenstein** [PixelRocket-Biz/cliff-michaels#236]
Have actual product cards in account page so they can buy the courses they dont have easily.
Gray out the card photo and then move to color when they hover over.

**Comment by cliffmichaelsgithub** [comment]
When user finishes a course video, it currently gets a check mark. Can that check mark be in the color red or dhow of the whole image grey fade a bit so it's more  discernible from the videos user has not watched?

**Comment by sethrubenstein** [comment]
Thats a sep issue please make it.

**Comment by cliffmichaelsgithub** [comment]
I'll make it separate if u think easy to do - or should we leave it alone? Just one of suggestions from Chase as a user.
