### ISSUE TITLE
Change WordPress Logo on Login Screen

### ISSUE THREAD

**Issue by sethrubenstein** [PixelRocket-Biz/cliff-michaels#239]
Make say cliffmichaels or cliffmichaels.com

Change fieldset css to not appear as normal fieldset.

FAQ modal - wont fire?

**Comment by cliffmichaelsgithub** [comment]
Can it say: "CliffMichaels.com Login"

**Comment by cliffmichaelsgithub** [comment]
Or one of these to avoid the impression that you're somehow tapping into the admin of our Wordpress. 
CliffMichaels.com Student Login
CliffMichaels.com User Login
