### ISSUE TITLE
Customer Service Messages 

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#241]
Does this bounce to the customer or to us? i.e: I clicked on the question mark thingy on one of our web pages to do a test ... our site then sent me the attached -- is that what the customer gets too or is that what I got because I'm admin. The message needs to be adjusted for the user so it says from: Support at CliffMichaels.com > email address is support=pixelrocket.biz@uservoice.com (this is an awkard sender to a user - likely to end up in their junk? YES ? NO ?

Where it says "Thanks for the message, we'll get back to you shortly." Can we instead say 

"Thanks for your message to CliffMichaels.com. You're our #1 priority & we will respond shortly. 95% of issues can be solved by reading our FAQ page. Also check your internet connection & make sure you have a compatible browser per our FAQ page. (Link FAQ page).

![screen shot 2015-03-06 at 10 31 13 am](https://cloud.githubusercontent.com/assets/6202539/6531238/7b5b5006-c3ec-11e4-9746-171bb7d74103.png)

**Comment by sethrubenstein** [comment]
Cliff see #238 - and put any customer service messaging you want in there please.
