### ISSUE TITLE
SOCIAL MEDIA IMAGE FIXES

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#243]
Can you show me how you changed those default images for my URLS or can you correct CliffMichaels.com and The4Essentials.com so my Facebook& LinkedIn pull the right images. I just pulled these images from my computer but i think you have th ebetter high res in our media library - i dont know how to attach them to Github

CliffMichaels.com should be this one. I think you need the one that is most close up and has me centered.
![cliff-header-left](https://cloud.githubusercontent.com/assets/6202539/6535695/d8ab18b8-c3fb-11e4-9a8f-a1386965d777.png)

The4Essetials.com currently pulls up a Google image. It should be the one that is Head Shot + Book Image
![cliff book](https://cloud.githubusercontent.com/assets/6202539/6535743/2ed0bd10-c3fc-11e4-9fef-c86feca61a63.png)

**Comment by sethrubenstein** [comment]
As i've said multiple times... the4essentials.com will always pull up a google image because its a redirect. You HAVE to use http://cliffmichaels.com/the-4-essentials/ when sharing on social networks.

As for the homepage social image I've changed that.

**Comment by cliffmichaelsgithub** [comment]
Noted! Thx for reminder !!
Sorry for Alzheimer's


On Mar 6, 2015, at 12:51 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


As i've said multiple times... the4essentials.com<http://the4essentials.com> will always pull up a google image because its a redirect. You HAVE to use http://cliffmichaels.com/the-4-essentials/ when sharing on social networks.

As for the homepage social image I've changed that.

-
