### ISSUE TITLE
4 Essentials E-Course > Video #4 of 41 course videos is in the product system but does not show up

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#245]
Its the video titled: How This Book is Structured
It is in the product system and even appears on the course page with other videos but gets the sorry msg

![screen shot 2015-03-09 at 1 51 47 pm](https://cloud.githubusercontent.com/assets/6202539/6564116/72c69cf6-c663-11e4-9c60-502c642ee91c.png)

**Comment by sethrubenstein** [comment]
That means you need to check the Vimeo Id that you have in the system w the corresponding Vimeo Id on Vimeo and make sire its correct. This error means the video as it was put into the system is incorrect.

**Comment by cliffmichaelsgithub** [comment]
Ready when you are for our call
