### ISSUE TITLE
Clean-up tools

### ISSUE THREAD

**Issue by sethrubenstein** [PixelRocket-Biz/cliff-michaels#251]
- [ ] Clean up the budget sheets edit entry. The calculation isn't working entirely properly.
- [ ] Change confirmation message to following:

You successfully saved this tool as - {TITLE}

View my saved entries for {name of tool} (button).
View all my other saved tools (button).

Keep up the great work!
Cliff Michaels

**Comment by cliffmichaelsgithub** [comment]
Thanks. I never did test these. Let me know when I should after fixes. Critical to my offering.
